config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :analyses
  resources :video_games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/analysis.rb
class Analysis < ApplicationRecord
  belongs_to :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :analysis
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
  has_one:analysis
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  before_action :set_analysis, only: [:show, :edit, :update, :destroy]

  # GET /analyses
  # GET /analyses.json
  def index
    @analyses = Analysis.all
  end

  # GET /analyses/1
  # GET /analyses/1.json
  def show
  end

  # GET /analyses/new
  def new
    @analysis = Analysis.new
  end

  # GET /analyses/1/edit
  def edit
  end

  # POST /analyses
  # POST /analyses.json
  def create
    @analysis = Analysis.new(analysis_params)

    respond_to do |format|
      if @analysis.save
        format.html { redirect_to @analysis, notice: 'Analysis was successfully created.' }
        format.json { render :show, status: :created, location: @analysis }
      else
        format.html { render :new }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analyses/1
  # PATCH/PUT /analyses/1.json
  def update
    respond_to do |format|
      if @analysis.update(analysis_params)
        format.html { redirect_to @analysis, notice: 'Analysis was successfully updated.' }
        format.json { render :show, status: :ok, location: @analysis }
      else
        format.html { render :edit }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_analysis
      @analysis = Analysis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analysis_params
      params.require(:analysis).permit(:title, :content, :rating)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:pseudo, :email, :password)
    end
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  before_action :set_video_game, only: [:show, :edit, :update, :destroy]

  # GET /video_games
  # GET /video_games.json
  def index
    @video_games = VideoGame.all
  end

  # GET /video_games/1
  # GET /video_games/1.json
  def show
  end

  # GET /video_games/new
  def new
    @video_game = VideoGame.new
  end

  # GET /video_games/1/edit
  def edit
  end

  # POST /video_games
  # POST /video_games.json
  def create
    @video_game = VideoGame.new(video_game_params)

    respond_to do |format|
      if @video_game.save
        format.html { redirect_to @video_game, notice: 'Video game was successfully created.' }
        format.json { render :show, status: :created, location: @video_game }
      else
        format.html { render :new }
        format.json { render json: @video_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_games/1
  # PATCH/PUT /video_games/1.json
  def update
    respond_to do |format|
      if @video_game.update(video_game_params)
        format.html { redirect_to @video_game, notice: 'Video game was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_game }
      else
        format.html { render :edit }
        format.json { render json: @video_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_games/1
  # DELETE /video_games/1.json
  def destroy
    @video_game.destroy
    respond_to do |format|
      format.html { redirect_to video_games_url, notice: 'Video game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_game
      @video_game = VideoGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_game_params
      params.require(:video_game).permit(:name, :editor, :description)
    end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/analyses/_form.html.erb
<%= form_with(model: analysis, local: true) do |form| %>
  <% if analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analysis.errors.count, "error") %> prohibited this analysis from being saved:</h2>

      <ul>
      <% analysis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :analysis_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :analysis_content %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :analysis_rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/analyses/edit.html.erb
<h1>Editing Analysis</h1>

<%= render 'form', analysis: @analysis %>

<%= link_to 'Show', @analysis %> |
<%= link_to 'Back', analyses_path %>

app/views/analyses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Analyses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @analyses.each do |analysis| %>
      <tr>
        <td><%= analysis.title %></td>
        <td><%= analysis.content %></td>
        <td><%= analysis.rating %></td>
        <td><%= link_to 'Show', analysis %></td>
        <td><%= link_to 'Edit', edit_analysis_path(analysis) %></td>
        <td><%= link_to 'Destroy', analysis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Analysis', new_analysis_path %>

app/views/analyses/new.html.erb
<h1>New Analysis</h1>

<%= render 'form', analysis: @analysis %>

<%= link_to 'Back', analyses_path %>

app/views/analyses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @analysis.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @analysis.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @analysis.rating %>
</p>

<%= link_to 'Edit', edit_analysis_path(@analysis) %> |
<%= link_to 'Back', analyses_path %>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pseudo %>
    <%= form.text_field :pseudo, id: :author_pseudo %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :author_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :author_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Pseudo</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.pseudo %></td>
        <td><%= author.email %></td>
        <td><%= author.password %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pseudo:</strong>
  <%= @author.pseudo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @author.password %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoGameReviews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/video_games/_form.html.erb
<%= form_with(model: video_game, local: true) do |form| %>
  <% if video_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video_game.errors.count, "error") %> prohibited this video_game from being saved:</h2>

      <ul>
      <% video_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :video_game_name %>
  </div>

  <div class="field">
    <%= form.label :editor %>
    <%= form.text_field :editor, id: :video_game_editor %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :video_game_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/video_games/edit.html.erb
<h1>Editing Video Game</h1>

<%= render 'form', video_game: @video_game %>

<%= link_to 'Show', @video_game %> |
<%= link_to 'Back', video_games_path %>

app/views/video_games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Video Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Editor</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_games.each do |video_game| %>
      <tr>
        <td><%= video_game.name %></td>
        <td><%= video_game.editor %></td>
        <td><%= video_game.description %></td>
        <td><%= link_to 'Show', video_game %></td>
        <td><%= link_to 'Edit', edit_video_game_path(video_game) %></td>
        <td><%= link_to 'Destroy', video_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video Game', new_video_game_path %>

app/views/video_games/new.html.erb
<h1>New Video Game</h1>

<%= render 'form', video_game: @video_game %>

<%= link_to 'Back', video_games_path %>

app/views/video_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @video_game.name %>
</p>

<p>
  <strong>Editor:</strong>
  <%= @video_game.editor %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video_game.description %>
</p>

<%= link_to 'Edit', edit_video_game_path(@video_game) %> |
<%= link_to 'Back', video_games_path %>